#!/usr/bin/env bash
# Transfer a file from client to a server
if [ "$#" -lt 4 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi
	PATH_TO_FILE="$1"
	IP="$2"
	USERNAME="$3"
	PATH_TO_SSH_KEY="$4"
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/

