#!/usr/bin/env bash
#redirecting to another page
echo -e "Nginx updates and installation\n"
sudo apt-get update -y -qq && \
sudo apt-get install nginx -y

echo -e "\nStarting nginx\n"

sudo service nginx start

sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
echo -e "Hello world!" >> /var/www/html/index.nginx-debian.html

sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart

echo -e "\nCompleted.\n"
