#!/usr/bin/env bash
#configures web-02 to be identical to web-01

echo -e "Updating checks\n"

function install() {
	command -v "$1" &> /dev/null
	#shellcheck disabled SC2181
	if [ $? -ne 0 ]; then
		echo -e "installing: $1$\n"
		sudo apt-get update -y -qq && \
		sudo apt-get install -y "$1" -qq
		echo -e "\n"
	else
		echo -e " ${1} is already installed.\n"
	fi
}

install nginx

echo -e "Setting up nginx\n"

sudo ufw allow "Nginx HTTP"

if [ -d "/var/www" ]; then
	sudo chown -R "$USER":"$USER" /var/www
	sudo chmod -R 755 /var/www
fi
#create directories if not present
for dir in /var/www/{html,error};do
	if ! [ -d "$dir" ]; then
		mkdir -p "$dir"
	fi
done

#new index
echo "Hello World!" > /var/www/html/index.html

#new error page
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

#backup default server file
sudo cp /etc/nginx/sites-enabled/default nginx-sites-enables_default.backup

server_config=\
"server {
		listen 80 default_server;
		listen [::]:80 default_server;
		root /var/www/html;
		index index.html index.htm index.nginx-debian.html
		server_name_;
		add_header X-Served-By \$hostname;
		location / {
			try_files \$uri \$uri/ =404;
		}
		if (\$request_filename ~ redirect_me){
			rewrite ^ https://th3-gr00t.tk/ permanent;
		}
		error_page 404 /error_404.html;
		location = /error_404.html {
			internal;
		}
}"

echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default

if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi
