#!/usr/bin/env bash
#a scirpt that configures IPv4 IPs to listen on port 80 servers
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
