#!/usr/bin/env bash
#tell a story with info from passwd
FILE=/etc/passwd
while IFS=: read w1 w2 w3 w4 w5 w6 w7
do
	printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" "$w1" "$w4" "$w6" "$w7" "$w3" "$w2" "$w5"
done < $FILE
