#!/usr/bin/env bash
#displays text as described
count=1
while [ $count -le 10 ]
do
	if [ $count - eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8 ]
	then
		echo "good luck"
	else
	fi
	((count++))
done
