#!/usr/bin/env bash
#changes ip on localhost

cp /etc/hots ~/hosts.new

sed -e '/\tlocalhost/c 127.0.0.2	localhost' -e '/\tfacebook.com/c 8.8.8.8	facebook.com' /etc/hosts > ~/new_hosts

cp -f ~/new_hosts /etc/hosts
